damoang/theme

- js/nariya.js
https://discord.com/channels/1223276360060108851/1224566245874073651
추천후 Alert 뜨는부분 코드 수정 안되어 있길래 반영해봅니다
> 추천 후 Alert 삭제

- layout/basic/css/style.css
1차로 최적화 했던 부분
개선이 있긴하나 ios크롬에서 여전히 부족한 느낌입니다
본서버에만 올리면 버벅이는 느낌이 있네요
추가 최적화를 해보았고 이것으로도 부족하면 웹폰트 전반에 대해 다시 살펴봐야할듯 합니다
일단 적용 부탁드립니다
> 웹폰트 최적화 2차

- css/default.css
- skin/board/basic/view/basic/view.skin.php
모바일에서 제대로 작동하지 않으므로 css로 대체합니다.
관련 링크: https://discord.com/channels/1223276360060108851/1227058329906581625
> 모바일에서 스크롤해야 이미지 크기 조정되는 현상 Fix

- layout/basic/css/style.css
- 게시물 목록의 제목인 list-group-item a 태그의 visited 처리
- 유지관리 요청 : https://damoang.net/bug/106?sfl=wr_subject&stx=%EC%9D%BD%EC%9D%80&sop=and
> 읽은 글은 제목 색이 변하는 기능

- js/nariya.js
실제 성능에 어떤 영향이 있었는지 측정해보지는 않았지만
불필요한 부분이므로 수정하였습니다
> nariya.js에서 트위터 스크립트 중복 삽입하는 문제 수정

- layout/basic/widget/wr-gallery/widget.php
- 모바일 2
- 데스크탑에 갈수록 점점 3, 4 열로 확장
확장할 수록 노출 개수가 변합니다.
> chore: 갤러리 섹션에서 포토 노출 개수 조정

- layout/basic/css/style.css
- .wr-name(사용자 이름) 영역을 제외하는 css 추가
> 이미 읽은 글 표시시에 사용자 이름 영역 제외

- skin/board/basic/comment/basic/comment.skin.php
- skin/board/basic/comment/true/comment.skin.php
(건의)댓글란 댓글 수정시 장문의 경우
https://damoang.net/free/165370
- "수정" 버튼 작동시, textarea 의 keyup 이벤트 호출하여, 이미 정의되어 있는 자동조정 기능이 작동되도록 수정
> 장문 댓글 수정시, 입력창의 크기 자동조절

- skin/board/basic/comment/basic/comment.skin.php
- skin/board/basic/comment/true/comment.skin.php
- textarea(댓글 입력창)와 button(댓글등록)에 tabindex 지정
유지관리 : [https://damoang.net/bug/1104?sfl=wr_subject&stx=댓글&sop=and](https://damoang.net/bug/1104?sfl=wr_subject&stx=%EB%8C%93%EA%B8%80&sop=and)
> 댓글 창에서 탭이동시 댓글 등록 버튼으로 이동

- skin/board/basic/comment/basic/comment.skin.php
- textarea의 tabindex를 0으로 잘못 수정하여, 1로 바로 잡았습니다.
> 댓글 창에서 탭이동시 댓글 등록 버튼으로 이동 - 수정

- skin/board/basic/view/basic/view.skin.php
> 본문 하단 메뉴 중복 제거

- js/nariya.js
- skin/board/basic/comment/basic/comment.skin.php
- skin/board/basic/view/basic/view.skin.php
https://damoang.net/free/236463
글 보고 후딱 만들었습니다.
> 추천/비추천 여부 확인 해서 버튼 색상 변경

- app/clip.comment.php
https://discord.com/channels/1223276360060108851/1228364931909423186
공백 문자 삽입 버튼 추가했습니다
검토해주세요~
> 코멘트에 공백문자 삽입 기능 추가

- layout/basic/component/menu.offcanvas.php
- layout/basic/component/sidebar.php
- layout/basic/head.sub.php
- 소모임 : 바다건넌당 -> 바다건너당 수정
- 가입인사 단축키 I로 확정
- 사이드메뉴 현행황 : 사용기/강좌 분리, 자료실 추가
- 추가된 게시판 단축키 현행화
> 메뉴, 사이드메뉴, 단축키 현행화

- skin/board/basic/view/basic/view.skin 1.php
- skin/board/basic/view/basic/view.skin.php
- skin/board/basic/view/true/view.skin.php
- 유지관리 문의: 게시판 본문의 우측상단의 불필요한 쓰기버튼 노출되어 있어 삭제 문의
> 게시글 본문의 불필요한 쓰기 버튼 삭제

- layout/basic/css/style.css
- 모바일/PC 환경에서 페이지네이션 버튼을 누르기 어렵다는 이슈
- pagination-sm의 padding과 font-size를 일괄 조정
> 페이지네이션 크기 조정

- app/clip.image.php
- skin/board/basic/comment/basic/comment.skin.php
- skin/board/basic/comment/true/comment.skin.php
코멘트에도 webp 이미지 사용이 가능하면 어떨까해서 올려봅니다
지원계획이 없으시면 reject 해주세요
> 코멘트에서 webp 사용

- js/nariya.js
트위터용 x.com 주소 대응
유튜브 timestamp 대응
2가지 수정입니다.
>  외부링크 변환 스크립트 수정

- skin/board/basic/list/list/list.skin.php
회원만 보기에서 게시물 리스트의 이미지 오버시 나오는 버그 수정
>  회원 보기 일때 미리 보기 제거

- layout/basic/component/member.offcanvas.php
- layout/basic/component/trans.offcanvas.php
> Arch 님 UI Custom

- css/default.css
- css/mobile.css
관련링크: https://discord.com/channels/1223276360060108851/1228982535065698335
> 긴 url이 본문영역을 벗어남 Fix

- skin/board/basic/comment/basic/comment.skin.php
> 댓글 추천내역 쿼리 성능 이슈로 사용 안함

- .gitignore
- google_cloud_ops_agent_provisioning/20240409-145713_431145/wrapper_script.log
- gitignore 파일 추가했습니다.
- gcp provisioning log 파일은 vcs에 없어도 되는 파일같아서 vcs에서 삭제했습니다.
> :see_no_evil: gitignore 추가 및 gcp log 삭제

- layout/basic/component/member.offcanvas.php
이 PR은 로그인 화면에 있는 가이드 메시지 ('This content is hidden on production') 을 숨김 처리합니다.
> 가이드 메시지 숨김 ('This content is hidden on production')

- layout/basic/component/member.offcanvas.php
- layout/basic/head.sub.php
- layout/basic/js/customui.js
1. 커스텀ui 기능이 head에 포함되어 있어 의도치 않은 현상들이 우려됩니다. 따라서 별도 파일로 분리하였습니다.
2. window load후에 커스텀ui 적용 function이 실행되어 적용이 늦습니다. 메뉴가 오른쪽에 있다가 왼쪽으로 바뀌는것이 눈에 보입니다. 따라서 이벤트 기다리지 않고 로딩 즉시 실행되도록 변경하였습니다
3. 로켓 로더 적용으로 로딩 즉시 실행하여도 타이밍이 늦는 문제가 있습니다. 따라서 커스텀ui는 로켓 로더 예외처리 하였습니다
> 커스텀ui 기능 속도 개선

- layout/basic/component/menu.offcanvas.php
- layout/basic/component/menu.php
- layout/basic/component/sidebar.php
> 내글내댓글 레이아웃 수정

- layout/basic/head.sub.php
- layout/basic/js/customui.js
커스텀UI 한번도 설정하지 않은 PC에서는 에러가 찍혀서 수정했습니다
head에서 set_ui_custom 호출하는 부분도 에러가 발생해서 주석처리하였습니다
(이 부분은 customui.js로 코드가 이동하여 head에는 필요하지 않아 보입니다)
> 커스텀UI 저장된 데이터 없을때 에러 발생하는 부분 처리

- INSTALL.md
Docker 말고 개인 서버를 운영하시는 분들이 다모앙 테마를 적용하실 때 참고해 주세요.
> 그누보드에 다모앙 테마 적용 메뉴얼

- layout/basic/head.sub.php
- layout/basic/js/custom_features.js
- skin/board/basic/category/basic/category.skin.php
- 게시판 오른쪽 위 검색 아이콘(돋보기) 왼쪽에 노트 아이콘 추가
- 공지가 표시되는 상태일 때 붉은 색으로 아이콘 표시
- 공지가 숨김 상태일 때 일반 색으로 아이콘 표시
- 아이콘 클릭시 숨김/표시 전환
- 공지가 숨김 상태일 때 게시판 접근 또는 새로고침 시 공지가 나타났다 사라지는 것은 의도 된 것으로 새로운 공지가 있는지 확인 할 수 있게 하기 위함 입니다. ( * 이 기능은 확인한 게시물 링크 색상을 다르게 표시할 때 확실히 알 수 있습니다. )
> 게시판 공지 숨기기 기능 추가

- layout/basic/js/custom_features.js
버그제보 : https://damoang.net/free/365578
> 공지 안 보기 시 열람중인 게시글도 리스트에서 안보이는 문제 해결

- app/clip.emo.php
- app/clip.icon.php
- app/clip.video.php
글쓸때 이모티콘, 아이콘 넣으려면 복사 붙여넣기 해야해서 불편한데
에디터에 바로 추가되도록 구현했습니다
> 글쓰기시 이모티콘, 아이콘 클릭하면 에디터에 바로 들어가게 구현

- layout/basic/js/custom_features.js
- skin/board/basic/category/basic/category.skin.php
megaphone 아이콘으로 변경 및 새로운 환경에서 처음 아이콘 토글이 동작하지 않을 수 있는 문제 수정.
> fix(board): 게시판에서 공지글 가리기 아이콘 변경

- layout/basic/js/custom_features.js
기존 저장된 데이터 형식이 달라 공지사항 감추기 설정이 저장되지 않는 문제 고침.
> fix(board): 공지사항 감추기가 동작하지 않을 수 있는 문제 고침

- layout/basic/js/darkmode.js
한번도 다크모드 직접 설정하지 않은 경우 -> auto로 뜨도록 수정
auto로 설정하면 글씨가 파란색으로 뜨는데 이부분도 정상적으로 표시되도록 수정
> 다크모드 기본값을 auto로 변경, auto에서 파란글씨 뜨는부분 수정

- layout/basic/head.php
- layout/basic/index.php
- layout/basic/tail.php
컨텐츠 영역과 사이드바 영역 높이에 따라 스크롤이 자연스럽게 느껴지지 않을 수 있는 문제 수정
> fix(layout): 사이드바와 연계된 스크롤 제어를 제거

- skin/board/basic/comment/basic/comment.skin.php
- skin/board/basic/list.skin.php
- skin/board/basic/list/list/list.skin.php
- skin/board/basic/view.skin.php
- skin/board/basic/view/basic/view.skin.php
`da_member_memo` 플러그인이 설치되어야 정상 동작하며,
`da_member_memo` 플러그인의 기능을 사용하기 위한 최소한의 변경이 필요하여 수정 함.
> feat(member_memo): 게시판에 회원 메모 기능 적용

- skin/board/basic/comment/basic/comment.skin.php
- skin/board/basic/comment/true/comment.skin.php
- skin/board/basic/list/gallery-sm/list.skin.php
- skin/board/basic/list/gallery/list.skin.php
- skin/board/basic/list/list-sm/list.skin.php
- skin/board/basic/list/list/list.skin.php
- skin/board/basic/list/list_admin/list.skin.php
- skin/board/basic/list/list_trueroom/list.skin.php
- skin/board/basic/list/webzine/list.skin.php
- skin/board/basic/view/free/view.skin.php
- skin/board/basic/view/true/view.skin.php
- skin/board/basic/view_comment.skin.php
- skin/board/free/comment/basic/comment.skin.php
- skin/board/free/comment/true/comment.skin.php
- skin/board/free/list.skin.php
- skin/board/free/list/gallery-sm/list.skin.php
- skin/board/free/list/gallery/list.skin.php
- skin/board/free/list/list-sm/list.skin.php
- skin/board/free/list/list/list.skin.php
- skin/board/free/list/list_admin/list.skin.php
- skin/board/free/list/list_trueroom/list.skin.php
- skin/board/free/list/webzine/list.skin.php
- skin/board/free/view.skin.php
- skin/board/free/view/basic/view.skin.php
- skin/board/free/view/free/view.skin.php
- skin/board/free/view/true/view.skin.php
- skin/board/free/view_comment.skin.php
- 게시판 스킨 basic와 free 스킨
- 그리고 이 스킨들에 포함된 목록, 글보기, 댓글 유형의 스킨에 전부 적용
> fix(member_memo): basic 스킨 외에도 전체에 회원 메모 적용

- layout/basic/component/menu.offcanvas.php
- layout/basic/component/sidebar.php
사이드바와 offcanvas에서 내글, 내댓글 링크가 서로 다른 문제 수정.
offcanvas 기준으로 링크를 통일 함.
> fix: 내글, 내댓글 링크 수정

- layout/basic/js/customui.js
#sidebar-site-menu #sidebar-sub-s0-10 a.nav-link -> #sidebar-site-menu a.nav-link.dropdown-toggle 로 셀렉터 변경
> 소모임 리스트 셀렉터 수정

- layout/basic/head.sub.php
cdn.jsdelivr.net -> fastly.jsdelivr.net 로 임시 교체
> chore: jsdelivr 서비스 문제의 영향을 받는 문제 고침

- layout/basic/widget/damoang-image-banner/widget.php
- layout/basic/widget/damoang-image-banner/widget.setup.php
> feat: 이미지 배너에 data-dd-action-name 속성 설정 추가

- layout/basic/js/customui.js
1. 에러 로그 삭제
2. 게시판 내글 및 내 댓글 검색 기능 추가
3. 확장버튼 시작시 열기로 변경
> custom ui 기능 추가 및 오류 수정

- layout/basic/component/member.offcanvas.php
- layout/basic/js/customui.js
> feat(customui): 회원메모 가리기 설정 추가

- app/widget.form.php
- app/widget.recommend.php
- layout/basic/index.php
- layout/basic/widget/wr-list-recommend/widget.lib.php
- layout/basic/widget/wr-list-recommend/widget.php
- layout/basic/widget/wr-list-recommend/widget.setup.php
추천 글 위젯의 추출 기간에 시간을 지정할 수 있도록 합니다.
> 추천 글 위젯 최근 n시간 이내 필터 적용

- skin/board/basic/view/basic/view.skin.php
- skin/board/basic/view/free/view.skin.php
- skin/board/basic/view/true/view.skin.php
- skin/board/free/view/basic/view.skin.php
- skin/board/free/view/free/view.skin.php
- skin/board/free/view/true/view.skin.php
> fix: 모바일에서 서명의 프로필이미지와 닉네임 정렬 고침

- layout/basic/component/menu.offcanvas.php
- layout/basic/component/sidebar.php
**앙실장님 요청**
사이드바 상단에 동일한 배너를 추가하고 사이드바가 아래로 내려갈 때 상단의 배너를 표시하도록 수정
> feat: 사이드바에 배너 위치 추가

- js/nariya.js
> 유튜브 2개 걸리는 현상 수정

- skin/board/basic/view/basic/view.skin.php
- skin/board/basic/view/free/view.skin.php
- skin/board/free/view/basic/view.skin.php
- skin/board/free/view/free/view.skin.php
https://discord.com/channels/1223276360060108851/1229335330906177576
목록 버튼에 쿼리 적용해서 보던 리스트로 돌아가게 했습니다.
> 게시물 아래쪽 목록버튼에 query값 적용

- layout/basic/css/style.css
- layout/basic/widget/wr-list-recommend/widget.php
- layout/basic/widget/wr-list/widget.php
- skin/board/basic/list/list/list.skin.php
- skin/board/free/list/list/list.skin.php
JS로 처리하던 코드를 CSS로 변경.
게시판 스킨, 위젯에서 기존에 적용된 곳에서 변경사항을 적용 함.
새창(새탭) 열기 동작이 안 되던 문제의 해결을 위함임.
> 글 목록에서 행 영역 전체 링크의 동작 개선

- app/board.skin.php
- skin/board/basic/write.skin.php
- skin/board/basic/write_update.head.skin.php
- skin/board/free/write.skin.php
- skin/board/free/write_update.head.skin.php
- git 에서 버전관리되지 않은 플러그인  파일이 변경되었습니다. rc source repo 에 반드시 변경사항을 추가하셔야 합니다.
- 적용할 코드는 https://github.com/damoang/theme/issues/138  코멘트 참고
- 프론트에서 체크, 백엔드 코드에서 권한 체크를 하도록 하였습니다.
> Issue 138 add write permit

- layout/basic/component/menu.offcanvas.php
- layout/basic/component/sidebar.php
내 글, 내 댓글 목록을 게시판 전체 검색 기능을 이용하도록 변경.
이 변경사항은 https://github.com/damoang/damoang-rc/pull/1 PR의 변경사항이 적용되어야 함.
---
https://github.com/damoang/damoang-rc/pull/1 적용이 필요하지만, 이 PR이 먼저 적용되어도 오류는 발생하지 않으며 단지, 글/댓글 필터가 적용되지 않은 상태로 결과를 보여주게되는 영향만 있습니다.
> feat: 내글, 내댓글 목록을 전체 검색 결과로 변경

- layout/basic/component/member.offcanvas.php
- layout/basic/js/customui.js
indexedDB를 활용한 메모 IP 기록 및 체크 기능 완료
> Custom UI - 빨간색 메모 IP 기록 기능 개발

- layout/basic/inc.menu.php
> 메뉴 삭제 - 가입인사, 커뮤니티

- js/nariya.js
> 유튜브 등 외부사이트 플러그인 정규표현식 수정

- js/nariya.js
> 외부사이트 플러그인 정규표현식 수정2

- js/nariya.js
아무리해도 갯수가 안맞아서 해보니까
정규식이 문제가 아니고 로직자체가 문제가 좀 있었네요..ㅠ
> 외부사이트 플러그인 링크 삭제 로직 수정

- skin/board/basic/view/basic/view.skin.php
- skin/board/basic/view/free/view.skin.php
- skin/board/free/view/basic/view.skin.php
- skin/board/free/view/free/view.skin.php
글 보기 하단에서 구글 광고와 이미지 배너가 너무 붙여서 표시되는 문제 고침.
> fix: 글 보기에서 구글 광고와 이미지 배너의 여백을 추가

- skin/board/free/list/list/list.skin.php
> feat: 글 목록에서 회원만 보기 아이콘을 "회원" 글자로 표시해 제목 앞으로 이동

- skin/board/basic/comment/basic/comment.skin.php
- skin/board/free/comment/basic/comment.skin.php
댓글에 첨부된 이미지는 원본 이미지가 표시되어 썸네일 생성을 추가했습니다.
> 댓글 이미지 썸네일 생성

- layout/basic/js/customui.js
1. 자기소개 링크 수정에 따른 mb_id 추출 방식 변경
2. IP메모 삭제 버그 수정
> Custom UI 자기소개 링크 수정에 따른 mb_id 추출 방식 변경

- app/clip.emo.php
이모티콘 페이지 열었을때 움직이지 않는 썸네일로 보입니다
마우스 오버 하면 움직이는 이모티콘이 보입니다
추후 이모티콘 추가시 파일명_thumb.webp 썸네일을 함께 추가해줘야합니다
> 이모티콘 정적로직 적용

- js/autosave.js
자동저장된 글 삭제하면 아무동작도 할수없는 버그가 있어 수정합니다
> 자동저장글 삭제시 버그 수정

- layout/basic/widget/wr-list-recommend/widget.php
메인 추천 글 위젯에 추천 수 표기를 추가합니다.
제안 글 : https://damoang.net/bug/3029
디스코드: https://discord.com/channels/1223276360060108851/1240854459232550922
> feat: 메인 추천글 위젯에 추천 수 표시 추가

- layout/basic/js/custom_features.js
jQuery 초기화 타이밍의 문제로 추정되는 스크립트 오류 수정
> fix: jquery 초기화 타이밍 문제 고침

- skin/board/free/list/list/list.css
- skin/board/free/list/list/list.skin.php
> feat: 회원만보기 글의 제목에 blur 효과 적용

- layout/basic/component/menu.offcanvas.php
차세대 개발 운영 게시판을 신설하였습니다.
차세대 인원의 레벨은 5입니다.
> 차세대 개발 운영 게시판 신설

- layout/basic/component/sidebar.php
> Revert "Nerv 메뉴 설정"

- skin/board/free/category/basic/category.skin.php
> fix: 공지사항 버튼 감추기로 인해 모바일에서 다른 항목들의 위치 문제 고침

- layout/basic/js/customui.js
img 에서 mb-photo 클래스가 삭제되어 다른 방법으로도 가져올 수 있게 수정하였습니다.
> 작성자 및 댓글 작성자 이미지 클래스 변경으로 가져오는 값 변경.

- layout/basic/component/member.offcanvas-customui.php
- layout/basic/js/customui.js
1. 앙맵 추가에 따라 메모블러 단축키를 U 로 변경.
2. 넘버패드 단축키 추가
3. 화면 재구성 로직 변경 - opacity 사용
4. 기타 버그 수정
> 메뉴 추가에 따른 단축키 변경 및 오류 수정

- layout/basic/group.php
- layout/basic/widget/wr-list-recommend/widget.php
- layout/basic/widget/wr-list/widget.php
소모임용 그룹 페이지를 위해 위젯을 새롭게 배치하고, 공통으로 이미지 배너 위젯을 배치했습니다.
> 그룹페이지에서 소모임용 위젯 배치

- layout/basic/css/style.css
글 목록에서 체크박스, 회원 메모 등의 UI를 가려 상호작용하지 못하는 문제를 수정합니다.
> feat: 글 목록에서 블록 링크가 체크박스 등의 UI와 상호작용을 방해하는 문제 고침

- skin/board/basic/list/list/list.skin.php
제목과 동일합니다.
공지사항 활성/비활성 안되는 문제 긴급 패치합니다.
> 게시판 목록 추천수 컬러세트 설정시 공지 활성/비활성 안되는 문제 조치

- layout/basic/css/style.css
- skin/board/basic/list/list/list.skin.php
[기능개선 요청 및 조치사항]
1. 추천수 기본 컬러세트 적용
- 투표로 결정된 2안 컬러세트를 기본으로 적용
2. 컬러세트 6종 추가
- 기본, 잿빛, 숲, 노랑, 다양, 없음
3. 추천수 0건일 때 컬러세트 미적용
- 기적님 의견 : 추천수가 0건일 땐 1건일 때와 구별하였으면 좋겠다.
- 추천수가 0건일 때는 부각시키지 않는 것도 타당한 것으로 보임.
개발/스테이징에 적용 후 검토 후 이견 없을경우 반영
> 추천수 기본 컬러세트 적용 및 컬러세트 6종 추가

- layout/basic/component/member.offcanvas-customui.php
- layout/basic/js/customui.js
1. IP메모 기능이 추가되었습니다.
2. 추천수 배경 설정 기능이 추가 되었습니다.
> Custom UI - IP메모 및 추천배경 설정 기능 추가

- layout/basic/index.php
> index 공지사항 상단으로 옮김

- layout/basic/index.php
> 광고 > 공지사항 위치 변경

- layout/basic/css/style.css
[개선사항]
추천수 0일 때 배경색이 지정되지 않다보니 약간의 이질감이 느껴짐에 따라 
흐릿하게 배경이 보이고 글자도 그에 맞게 약하게 보이도록 조치함
> 추천수 0일 때 가독성 조절

- layout/basic/js/customui.js
[요청사항]
https://damoang.net/bug/3722#c_3762
추천수 단계별 배경색 변경되지 않는 문제 조치 요청
[조치사항]
단계별 추천수 배경색 지정시 속성명이 누락되어 색상이 적용되고 있지 않음
속성명 추가하여 패치함
> 단계별 추천수 색상 지정시 속성명 누락 조치

- layout/basic/component/member.offcanvas-customui.php
- layout/basic/js/customui.js
> 터치 제스처 기능 추가

- layout/basic/component/member.offcanvas-customui.php
- layout/basic/js/customui.js
1. 사이드 및 메인 메뉴 소모임 3개 랜덤 표시 및 추천 기능 끄기 버튼 추가
2. 소모임 타이틀 옆 단축키 등록 버튼 추가.
> 사이드 메뉴 소모임 랜덤 표시 및 단축키 등록 버튼 추가

- layout/basic/head.sub.php
- layout/basic/js/customui.js
> Custom UI - customui js ver 수동변경

- app/board.skin.php
**AS-IS**
- 스킨 설정에서 댓글 이미지 업로드 제한 설정을 토글할 수 있습니다.
- 토글 여부에 따라 용량 제한을 설정할 수 있습니다.
- [dmg-gnu_PR#56](https://github.com/damoang/dmg-gnu/pull/56)
> feat: 스킨 설정에서 댓글 이미지 업로드 제한

- layout/basic/component/member.offcanvas-customui.php
- layout/basic/head.sub.php
- layout/basic/js/customui.js
1. 소모임 추천 목록 관련 문제 수정했습니다.
2. 마이메뉴 이미지 사이지 수정했습니다.
3. 터치 제스처 동작 범위 및 화면 전환시 로직 수정했습니다.
> Custom UI - 소모임 추천 문제 수정

- layout/basic/component/new.offcanvas.php
- layout/basic/widget/wr-gallery/widget.php
- layout/basic/widget/wr-list-recommend/widget.php
- layout/basic/widget/wr-list/widget.php
- layout/basic/widget/wr-webzine/widget.php
- skin/board/basic/comment/basic/comment.skin.php
- skin/board/basic/comment/true/comment.skin.php
- skin/board/basic/list/gallery-sm/list.skin.php
- skin/board/basic/list/gallery/list.skin.php
- skin/board/basic/list/list-sm/list.skin.php
- skin/board/basic/list/list/list.skin.php
- skin/board/basic/list/list_admin/list.skin.php
- skin/board/basic/list/list_trueroom/list.skin.php
- skin/board/basic/list/webzine/list.skin.php
- skin/board/basic/view/basic/view.skin.php
- skin/board/basic/view/free/view.skin.php
- skin/board/basic/view/true/view.skin.php
- skin/member/basic/memo.skin.php
- skin/member/basic/memo_view.skin.php
- skin/new/basic/new.skin.php
- skin/qa/basic/list.skin.php
- skin/qa/basic/view.answer.skin.php
- skin/qa/basic/view.skin.php
- skin/search/basic/search.skin.php
- skin/search/basic/tag.skin.php
임의 지정된 포맷을 제거하고 damoang/dmg-gnu#61 기본 날짜 포맷으로 적용.
> feat: 목록 및 내용보기 등에서 na_date()를 이용한 날짜 포맷 변경
