damoang/theme

layout/basic/css/style.css

웹폰트를 Noto Sans KR 단독 사용하도록 되어있었는데
이 폰트가 렌더링 성능에 큰 영향을 끼치고 있었습니다. 스크롤시 흰 화면 나오는 원인이었구요
그래서 웹폰트를 제거하면 어떨까 했는데 레이아웃도 살짝 이상해지고 로컬 폰트만으로 화면을 그리면 예뻐보이지 않아서
Roboto 를 우선으로  사용하도록 하였더니 속도 이슈도 해결되고 디자인도 망치지 않는 결과가 나왔습니다
스크롤바 2개 나오고 상단바 동작 없어지는 사이트 이펙트 수정을 위해 scroll-y 도 다시 제거하였습니다

웹폰트 렌더링 성능개선 및 스크롤 관련 사이드 이펙트 수정

---

layout/basic/widget/wr-list/widget.php
skin/board/basic/list/list/list.skin.php

https://discord.com/channels/1223276360060108851/1226557123782250536
해당 이슈이며 게시글 리스트에서 제목 부분을 클릭하면 a태그와 onclick이벤트가 중복되어 페이지 요청이 2번 날아갑니다
서버부하가 더 발생할 수 있어 수정 필요해보입니다
추후 개선 가능성:
onclick이벤트 방식보다는 a태그를 텍스트만이 아닌 li상위로 올려서 전체영역에 링크가 걸리게 하는게 더 나은 방향이라고 봅니다
다만 이렇게 하면 트리구조가 바껴서 css수정까지 필요한 부분이 확인되어 추후 반영하는 것이 바람직해보입니다.

게시글 제목 텍스트 부분 클릭시 서버요청 2번 하는 버그 수정

---

skin/board/basic/list/list/list.skin.php

https://damoang.net/bug/866
위와 같은 이슈로 작성자 팝오버 메뉴를 사용할수가 없어서 onclick되는 영역을 구분하여 동작하는 로직을 넣었습니다
작성자 팝오버 메뉴용 로직이 테마에 없고 그누보드 코드에 있는것으로 보여 자바스크립트 코드로 우회하였습니다

게시글 제목 클릭 후 페이지 이동하는 영역 조정

---

skin/board/basic/view/basic/view.skin.php

본문 페이지에서 본문과 목록 사이에 목록으로 이동 버튼을 추가합니다.

본문과 목록 사이에 목록으로 이동 버튼 추가

---

skin/board/basic/view/basic/view.skin.php
skin/board/basic/view/true/view.skin.php

https://discord.com/channels/1223276360060108851/1228210882560131143
서명영역 레이아웃 변경하였습니다
아이콘에 회원이미지와 동일한 것이 노출되면 좋겠습니다.
닉 옆에 '레벨' 글자 삭제
닉 아래 진행바 삭제
추가로 서명영역 화면사이즈에 따라 가변으로 동작.

서명영역 레이아웃 변경

---

layout/basic/css/style.css

- 기능으로 추가된 읽은글 표시에 대해서 다크 테마에서 색깔 구분이 명확했으면 좋겠다는 의견이 많이 있어서, 추가 반영을 하였습니다.
- 기존 light/dark 테마일때 공통적용한 color를 각 테마에 어울리는 색상으로 개별 적용.

다크 테마에서 읽은글 css 적용

---

css/nariya.css

- 모바일 환경에서 버튼의 "스크랩" 글씨가 줄바꿈되어 표시됨

게시글 본문의 스크랩 버튼 ui 이슈

---

layout/basic/head.sub.php

깜빡임 현상으로 인해 `document.documentElement.style.visibility = 'hidden';` 제거합니다.

깜빡임 현상 fix

---

css/fonts/NEXON_Lv2_Gothic.css
css/mobile.css
css/nariya.css
js/common.js
js/wrest.js

9년된 브라우저들 지원 코드삭제
사파리 8.4 이하
오페라 12.1 이하
IE 9 이하
wrest.js trim 함수 없던시절 자체구현체 -> trim 으로 변경
width, heigth, border 같은줄 중복삭제
위에 적힌 옛날 브라우저들 CSS 벤더 프리픽스 삭제
IE 9 이하지원 코드 삭제

9년 넘은 구형브라우저 지원 코드 삭제

---

layout/basic/component/sidebar.php
layout/basic/index.php
layout/basic/widget/damoang-image-banner/widget.php
layout/basic/widget/damoang-image-banner/widget.setup.php

메인과 사이드의 배너 기능을 나리야 빌더의 위젯으로 만들어 대체하였습니다.
- 이미지 주소와 링크를 입력 받아 이미지 배너를 출력하는 (신) 나리야 빌더용 위젯
- 이미지 배너는 랜덤 출력
- 메인 현재 이미지 배너 위치
- 사이드바 현재 이미지 배너 위치

feat: 배너 부분을 위젯으로 대체

---

js/nariya.js

현재 다모앙은 목록에서 마우스가 지나가기만해도 썸네일을 표시하기 위해 이미지를 다운받습니다.
유저는 그저 마우스만 슥 지나가도 썸네일이 떠서 깜빡거릴뿐더러 트래픽이 소모됩니다.
트래픽 소모를 줄이기 위해 500ms 뒤에도 마우스가 그 자리에 있으면 썸네일이 표시됩니다.

목록 마우스 오버시 썸네일 500ms 시간 차  추가

---

app/widget.form.php

위젯 설정 시 '초기화' 버튼이 실수로 동작하여 설정이 초기화될 수 있는 문제 방지
나리야 위젯설정 기능에서 "초기화" 버튼이 먼저 폼을 전송하도록 구현되어있어서 실수로 위젯 설정이 초기화 될 수 있는 문제.

fix: 위젯 설정에서 폼을 초기화하는 문제 고침

---

layout/basic/component/menu.offcanvas.php
layout/basic/component/sidebar.php
layout/basic/js/customui.js

메뉴 항목마다 링크 대상에 따른 이름을 가진 CSS Class 를 추가 함.
`da-menu--`로 시작하는 클래스명으로 지정됨.
단축키 설정 등에서 활용할 수 있음.
- PHP 8 호환성 문제 수정

feat: 메뉴에 항목마다 이름을 가진 CSS class 추가

---

skin/board/basic/view/basic/view.skin.php

관련 이슈: https://discord.com/channels/1223276360060108851/1235944498090082334
이미지에 삽입한 링크와 이미지 크게보기 링크가 중첩으로 달리는 문제가 있으므로
위와 같은 상황에서 이미지 크게보기 링크를 제거합니다.

<a> 태그 중복 제거 코드 추가

---

layout/basic/_head.sub.php
layout/basic/head.sub.php

js_ver 태그는 밖에있고 관리하기도 신경쓰이고
버전태그는 파일 변경할때 같이 바꿔주는게 좋지 않을까요?
js/css 캐시가 1년이라 당장바뀌어야합니다

nariya.js 버전 태그 변경

---

js/nariya.js
layout/basic/js/customui.js

미리보기 끔 설정으로 인해 bootstrap의 `popover` 패널이 표시되지 않는 문제 고침.
`popover` 패널을 감추는 대신 미리보기 항목에 `bs-popover-disabled` 속성을 추가하여 미리보기 기능의 비활성화 상태를 사용함

fix(customui): #141 미리보기 끔 설정 사용 시 `popover` 표시 문제 고침

---

skin/board/basic/category/basic/category.skin.php
skin/board/free/category/basic/category.skin.php

공지사항이 없을 때도 아이콘이 표시되어 동작하지 않는 것처럼 보이거나 의도하지 않게 공지사항 감추기 상태가 변경될 수 있는 사용성 문제를 개선.
디스코드 이슈: https://discord.com/channels/1223276360060108851/1240384078767849613

feat: 공지사항 감추기 버튼을 공지사항이 있을 때만 표시하도록 변경

---

layout/basic/css/style.css
skin/board/basic/list/list-sm/list.skin.php
skin/board/basic/list/list/list.skin.php
skin/board/basic/list/list_admin/list.skin.php
skin/board/basic/list/list_trueroom/list.skin.php
skin/board/free/list/list-sm/list.skin.php
skin/board/free/list/list/list.skin.php
skin/board/free/list/list_admin/list.skin.php
skin/board/free/list/list_trueroom/list.skin.php

리스트에서 제목 길이가 길어지더라도 한줄로 정리되어 표시됩니다
마우스 오버하면 툴팁으로 전체 제목이 표시됩니다
관리자 모드에서 제목길이(모바일 제목 길이 포함)를 길게 수정해주셔야합니다. 100자이상으로 놔도 됩니다.
(전체 제목인 wr_subject를 쓸까 했으나 그누보드에서 뭔가 제목에 대해 처리하는 로직이 있는걸로 보입니다. 그러므로 subject 를 그대로 쓰면서 관리자모드에서 수정하는 것이 안전)

제목영역 레이아웃 정리 및 툴팁 적용

---

layout/basic/css/style.css
skin/board/basic/list/list-sm/list.skin.php
skin/board/basic/list/list/list.skin.php
skin/board/basic/list/list_admin/list.skin.php
skin/board/basic/list/list_trueroom/list.skin.php
skin/board/free/list/list-sm/list.skin.php
skin/board/free/list/list/list.skin.php
skin/board/free/list/list_admin/list.skin.php
skin/board/free/list/list_trueroom/list.skin.php

유저 사이드뷰 표시를 위해 overflow 처리 방식을 변경했었는데,
파이어폭스에서 정상적으로 표시되지 않는 리포트를 받아
overflow 처리방식은 hidden으로 원복하고,
사이드뷰 position방식을 변경하는 방식으로 다시 구현했습니다.

제목 말줄임 표시 로직 파이어폭스에서 적용안되는 문제 해결

---

skin/board/basic/comment/basic/comment.skin.php

기존 댓글 버튼들 사이에 복사 버튼을 만들고 
복사 버튼을 누르면 화면 가운데에 "댓글 주소가 복사되었습니다"라고 1초 정도 메시지가 나왔다가 사라지게 했습니다.
복사한 내용은 클립보드에 복사되며 필요한 곳에 붙여넣기 하여 사용할 수 있습니다.

댓글 주소 복사 기능 추가

---

skin/board/basic/comment/basic/comment.skin.php

다음과 같은 사항을 포함합니다.
- 대댓글에 답변 대상자의 닉네임 표시를 추가
- `@작성자님에게 답변`
- 댓글들을 구분할 때 시선을 방해하는 중복된 아이콘을 변경
- "답변" 버튼의 아이콘 변경
- 글 작성자의 댓글을 구분하던 배경색을 차이를 증가 시켜 구분하기 좀 더 쉽도록 개선

댓글 목록의 시인성 개선

---

layout/basic/css/style.css
skin/board/basic/comment/basic/comment.skin.php

[증상]
폰트사이즈, 줄간격을 기본 설정보다 작게 조절하면
게시판 목록 제목 옆의 아이콘 그룹외 항목들이 줄간격이 틀어져 버립니다.
[조치]
style.css 파일내 해당 요소의 top 속성을 제거하고 중앙 정렬 속성을 추가하였습니다.
[개선 전]
[개선 후]
--------------
[증상]
미 로그인시 댓글 복사 함수가 없다고 나오며 복사 안됨
[조치]
복사 버튼은 로그인한 회원에게만 노출하도록 수정

폰트사이즈/줄간격 조절시 게시글 목록 아이콘그룹, 카테고리,댓글수 라인 맞지 않는 문제 조치

---

layout/basic/component/menu.offcanvas.php
layout/basic/component/sidebar.php
layout/basic/css/style.css
layout/basic/inc.menu.php
layout/basic/js/customui.js

메뉴의 아이콘, 단축키 표시, 메뉴명을 정렬하고 단축키 표시를 고정된 너비로 표시하게 개선했습니다.
AS-IS
TO-BE

사이드바 메뉴의 아이콘, 단축키 표시를 정렬

---

layout/basic/index.php
layout/basic/tail.php

메인페이지에서 누락된 태그로 인해 사이트 레이아웃 깨지는 문제를 수정하고 푸터 영역의 모양새를 정리했습니다.
AS-IS
TO-BE

메인페이지에서 푸터가 깨지는 문제 수정 및 UI 개선

---

layout/basic/component/noti.offcanvas.php
layout/basic/head.php
layout/basic/tail.php

커뮤니티의 불만이 많았던 알림 기능을 토스트 알림을 제거하고 헤더 영역 아이콘으로 표시하도록 변경했습니다.
알림 아이콘이 추가되어 좁아진 아이콘 영역에서 테마 컬러셋 변경 버튼을 메뉴 패널로 옮겼습니다.

새 알림이 있을 때 toast 대신 헤더 영역에 아이콘에 표시하도록 변경

---

layout/basic/css/style.css
layout/basic/widget/wr-list-recommend/widget.php
skin/board/basic/category/basic/category.skin.php
skin/board/basic/list/list/list.skin.php

[개선 요청사항]
게시판 목록의 추천수를 앞에 배치하고 크게 의미 없는 글 번호는 뒤로 빼거나 제거
[조치]
1. 추천수를 맨 앞으로 배치
2. 글 번호는 삭제
- PC, 모바일 통틀어 글번호를 유의미하게 사용하는 곳은 없는 것으로 보임(모바일은 이미 글 번호 노출하지 않고 있음)
- 일단, 완전 삭제하지 않고 글 번호는 주석 처리하여 보이지 않게 처리
- 의견 청취 후 완전 삭제 또는 되살리는 방향으로 진행
3. 추천수에 따라 컬러세트 지정(메인 추천수, 게시판 목록 추천수)
- 총 4단계에 걸쳐 컬러를 지정함
- 5개 이하, 5개 초과 10개 이하, 10개 초과 50개 이하, 50개 초과
- 색상은 다크/라이트 고려하여 적당한 색상으로 지정하였으며 추 후 색상에 대한 의견이 있을 경우 보완 조치함
4. 공지글은 추천수를 표시하지 않고 "공지" 텍스트로 표시함

메인, 게시판목록 추천수 컬러세트 지정 및 노출 위치 수정

---

layout/basic/index.php

[증상]
메인 공지사항 구분선 위치가 타이틀 위로 보여짐
광고 타이틀의 구분선이 보이지 않음
[조치]
공지사항 구분선 위치 조정
광고 고분선 추가

메인 공지 구분선 어긋나는 것 수정

---

layout/basic/css/style.css
layout/basic/tail.php
skin/board/basic/category/basic/category.skin.php
skin/board/basic/list/list/list.css
skin/board/basic/list/list/list.skin.php

[증상]
모바일에서 제목 하단의 댓글, 추천수 등의 정보 출력시 균등분할로 보이는 문제 발생
[조치]
margin: auto속성을 모바일에선 적용하지 않도록 처리
[개선사항]
1. 자신이 작성한 글은 글 목록에서 배경색을 강조하여 표시 함
2. 게시판 목록에 내가 작성한 글, 댓글 조회하는 버튼 추가
3. Footer 영역 모바일 뷰 개선
- 폰트 사이즈 9px ~ 14px 범위 내에서 조절되도록 조치, 그 외 약간의 간격 조절

모바일에서 제목 하단 영역 정렬 안 맞는 문제 조치, 자신이 작성한 글 강조,내글 내댓글 조회버튼 추가

---

skin/board/basic/category/basic/category.skin.php

[문제]
게시판 목록의 내글, 내댓글 버튼 클릭시
내 글 누르면 댓글이, 내 댓글 누르면 내 글이 나오고 있습니다.
[조치]
내 글, 내 댓글 조회시 보내는 코드 반대로 변경합니다.

내글/내댓글 조회시 목록 반대로 나오는 문제 조치

---

layout/basic/css/style.css
skin/board/basic/list/list/list.skin.php

https://discord.com/channels/1223276360060108851/1247003869318483978
표가 많은 2안을 기준으로 합니다.
나머지도 소중하다고 생각되어 모두 컨트롤 할 수 있도록 준비했습니다.
이 부분은 커스텀 UI 담당자분께 맡기겠습니다.
- 추천 수 (모바일)
- `me-2 d-none` 제거
- `order-last ms-auto` 추가
- 댓글 수
- `d-none d-md-inline-block` 추가
- 추천 수
- `d-none` 추가
- 댓글 수
- `d-none` 제거
- 추천 수 (모바일)
- `d-none` 제거
- 따봉 아이콘에 `d-none` 추가
- 댓글 수
- `d-none d-md-inline-block` 추가
- 이름
- `ms-auto order-last` -> `me-auto order-1` 변경
- 하위 `.profile_img`에 `d-none d-md-inline-block` 추가
- 추천 수
- `d-none` 추가
- 댓글 수
- `d-none` 제거

모바일 목록 UI 개선

---

skin/board/basic/comment/basic/comment.css
skin/board/basic/comment/basic/comment.skin.php

[개선사항]
글 작성자가 등록한 댓글 강조 기능은 있으나
로그인 한 사용자가 자신이 작성한 댓글을 강조하여 보는 기능이 없어서
강조하도록 기능 추가 함.
[조치]
기존에 글 작성자가 등록한 댓글 강조하는 기능에 
로그인 한 사용자가 작성한 댓글을 강조하는 조건을 추가하여 구현
[개선된 화면 : Dark, Light]

내가 작성한 댓글 강조

---

skin/board/basic/list.skin.php

[기능수정]
롤링 공지의 노출 시간을 3초에서 4초로 수정합니다.
문장이 길 경우 읽다가 사라지는 느낌이라 약간 시간을 늘렸습니다.

롤링 공지 노출 시간 조절

---

layout/basic/widget/advertiser/widget.php
layout/basic/widget/advertiser/widget.setup.php
page/advertiser.php

광고주모음 페이지인 '광고앙' 페이지를 위한 위젯을 추가하였습니다. 
* 현재의 긴배너와 사이드배너 자동 동기화 출력
현재 광고주 광고 배너 목록을 업데이트하기위해 더이상 php 코드를 수정하지 않아도  헤드배너와 사이드배너 위젯을 통해 등록중인 긴배너와 사이드배너들이 '광고앙'페이지 (/content/advertiser)에 자동으로 나옵니다.
*직홍게 광고주 리스트를 위젯 데이터로 관리
또한 직홍게 리스트를 위젯으로 관리할 수 있습니다. '광고앙' 페이지에서 위젯설정을 눌러보면 '광고주모음 위젯설정' 버튼이 나오고 거기에서 직홍게 광고주 목록을 업데이트 할 수 있습니다.

광고앙 모음 페이지를 위한 위젯 추가(advertiser.php를 하드코딩 할 필요없도록 수정)
